name: Weekly Build Validation
run-name: Validation run ${{ github.run_number }} by @${{ github.actor }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Build-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Select 'all' target
        run: sed -i "s/checksum/all/g" ${{ github.workspace }}/resources/options
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.11.0
        with:
          context: ${{ github.workspace }}
          push: false
          tags: xtide-builder:latest
      - run: mkdir -p ${{ github.workspace }}/src
      - uses: addnab/docker-run-action@v3
        with:
          image: xtide-builder:latest
          options: --user 1001:121 -v ${{ github.workspace }}/src:/src
          run: |
            echo "Building with:"
            cat /options
            cd /
            ./xtide_build.sh
      - name: Verify output
        run: |
          mkdir -p ${{ github.workspace }}/compare
          cd ${{ github.workspace }}/compare
          RELEASE=$(cat ${{ github.workspace }}/src/trunk/XTIDE_Universal_BIOS/Inc/Revision.inc | xargs)
          echo "Compare output with official binaries @ r$RELEASE."
          EXITCODE=0
          echo "<h2>Validation Results</h2>" >> $GITHUB_STEP_SUMMARY
          echo "<table>" >> $GITHUB_STEP_SUMMARY
          echo "<tr><th>Filename</th><th>Size</th><th>Actual</th><th>Expected</th><th>Hash</th><th>Actual</th><th>Expected</th><th>Valid?</th></tr>" >> $GITHUB_STEP_SUMMARY
          for i in ${{ github.workspace }}/src/trunk/XTIDE_Universal_BIOS/Build/*.bin; do
            BINNAME=$(basename $i)
            wget -q https://www.xtideuniversalbios.org/binaries/r$RELEASE/$BINNAME
            EXPECTEDHASH=$(tail -c +64 $BINNAME | md5sum | cut -d ' ' -f 1)
            EXPECTEDSIZE=$(stat -c%s $BINNAME)
            ACTUALHASH=$(tail -c +64 $i | md5sum | cut -d ' ' -f 1)
            ACTUALSIZE=$(stat -c%s $i)
            echo -n "<tr><td>$BINNAME</td><td></td><td>$ACTUALSIZE</td><td>$EXPECTEDSIZE</td><td></td><td><code>$ACTUALHASH</code></td><td><code>$EXPECTEDHASH</code></td>" >> $GITHUB_STEP_SUMMARY
            if [[ $EXPECTEDSIZE == $ACTUALSIZE && $EXPECTEDHASH == $ACTUALHASH ]]; then
              echo "<td>✅</td></tr>" >> $GITHUB_STEP_SUMMARY
            else
              echo "<td>❌</td></tr>" >> $GITHUB_STEP_SUMMARY
              EXITCODE=1
            fi
          done
          echo "</table>"  >> $GITHUB_STEP_SUMMARY
          exit $EXITCODE
        shell: bash
          
  
      - run: echo "🍏 This job's status is ${{ job.status }}."
