name: Weekly Build Validation
run-name: Validation run ${{ github.run_number }} by @${{ github.actor }}
on: 
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'

jobs:
  Build-Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build and push Docker images
        uses: docker/build-push-action@v6.11.0
        with:
          context: ${{ github.workspace }}
          push: false
          tags: xtide-builder:latest
      - run: mkdir -p ${{ github.workspace }}/src
      - uses: addnab/docker-run-action@v3
        with:
          image: xtide-builder:latest
          options: --user 1001:121 -v ${{ github.workspace }}/src:/src
          run: |
            nasm --version > /src/nasmver.txt
            echo "Building with:"
            cat /options
            cd /
            ./xtide_build.sh
      - name: Test output
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-i386 socat
          qemu-system-i386 -cpu 486 -option-rom ${{ github.workspace }}/src/trunk/XTIDE_Universal_BIOS/Build/ide_386.bin -nic none -hda ${{ github.workspace }}/.github/workflows/resources/validation_hdd.img -display none -monitor unix:qemu-monitor-socket,server,nowait &
          echo "Started QEMU, wait 20 sec."
          sleep 20
          DUMPCOMMAND="screendump ${{ github.workspace }}/capture.png"
          echo "$DUMPCOMMAND" | socat - unix-connect:qemu-monitor-socket
          echo "quit" | socat - unix-connect:qemu-monitor-socket
      - uses: devicons/public-upload-to-imgur@v2.2.2
        name: Upload test output
        id: imgur_step
        with:
          path: ${{ github.workspace }}/capture.png
          client_id: ${{ secrets.IMGUR_APP_ID }}
      - name: Verify output
        env:
          IMG_URL: ${{ fromJSON(steps.imgur_step.outputs.imgur_urls)[0] }}
        run: |
          mkdir -p ${{ github.workspace }}/compare
          cd ${{ github.workspace }}/compare
          RELEASE=$(cat ${{ github.workspace }}/src/trunk/XTIDE_Universal_BIOS/Inc/Revision.inc | xargs)
          NASMVER=$(cat ${{ github.workspace }}/src/nasmver.txt)
          echo "Compare output with official binaries @ r$RELEASE."
          EXITCODE=0
          echo "<h2>Build Results</h2>" >> $GITHUB_STEP_SUMMARY
          echo "<p>NASM Version: $NASMVER</p>" >> $GITHUB_STEP_SUMMARY
          echo "<table>" >> $GITHUB_STEP_SUMMARY
          echo "<tr><th>Filename</th><th>Size</th><th>Hash</th></tr>" >> $GITHUB_STEP_SUMMARY
          for i in ${{ github.workspace }}/src/trunk/XTIDE_Universal_BIOS/Build/*.bin; do
            BINNAME=$(basename $i)
            ACTUALHASH=$(tail -c +64 $i | md5sum | cut -d ' ' -f 1)
            ACTUALSIZE=$(stat -c%s $i)
            echo "<tr><td>$BINNAME</td><td>$ACTUALSIZE</td><td><code>$ACTUALHASH</code></td></tr>" >> $GITHUB_STEP_SUMMARY
          done
          echo "</table>"  >> $GITHUB_STEP_SUMMARY
          echo "![Image]($IMG_URL)"
          exit $EXITCODE
        shell: bash

      - run: echo "🍏 This job's status is ${{ job.status }}."
